### ISSUE TITLE
Error when deleting report finding

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#366]
## Bug
Hi all.  With the latest code base (git pulled this morning), we're getting errors when deleting a finding from a report:

`Error!! Check the process dump for the error or turn show_exceptions on to show in the web interface.
`
The finding does get deleted from the report, but it's very annoying and slows down workflow.

The console shows the following in STDOUT:

```
2017-10-16 09:43:20 - NoMethodError - undefined method `title' for nil:NilClass:
	/opt/serpico-04-09/routes/report.rb:1120:in `block in <top (required)>'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.5.5/lib/rack/handler/webrick.rb:60:in `service'
	/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'


```

Any idea what is causing this and how to fix?

Thanks,

Sean

**Comment by giper45** [comment]
Hi, have you using a customized template or a default installed template?  
If you're using a customized template, could you try with a default installed template?
It doesn't happen with my templates just try... could you show some portion of  the template that you 're using?

**Comment by BuffaloWill** [comment]
@ITGSean, just confirmed the issue. Reviewing a fix now.

**Comment by BuffaloWill** [comment]
@ITGSean, thank you for submitting the bug. Just pushed a fix.

**Comment by ITGSean** [comment]
Thanks Will - confirmed working fix :+1:
