### ISSUE TITLE
"Implicit Conversion of nil to String" whenever I try to upload a png image attachment

### ISSUE THREAD

**Issue by arikalfus** [SerpicoProject/Serpico#529]
# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Describe the issue and steps to reproduce

1. Clone a new instance of Serpico from the master branch on an Ubuntu system. Using Ruby 2.3.3 as that is what is specified in the Gemfile.
2. Run `init_serpico.sh` followed by `ruby serpico.rb`.
2. Create a new report.
3. Add some findings.
4. Go to "Upload New Attachment" and attempt to upload any .png file (did not test with .jpg).
5. Get an error and stack trace.

```
192.168.1.157 - - [03/Nov/2018:18:37:05 EDT] "GET /report/1/attachments HTTP/1.1" 500 167109
https://192.168.1.162:8443/report/1/upload_attachments -> /report/1/attachments
192.168.1.157 - - [03/Nov/2018:18:37:06 -0400] "GET /__sinatra__/500.png HTTP/1.1" 200 24378 0.0079
192.168.1.157 - - [03/Nov/2018:18:37:06 EDT] "GET /__sinatra__/500.png HTTP/1.1" 200 24378
https://192.168.1.162:8443/report/1/attachments -> /__sinatra__/500.png
192.168.1.157 - - [03/Nov/2018:18:37:22 -0400] "POST /report/1/upload_attachments HTTP/1.1" 303 - 0.1973
192.168.1.157 - - [03/Nov/2018:18:37:21 EDT] "POST /report/1/upload_attachments HTTP/1.1" 303 0
https://192.168.1.162:8443/report/1/upload_attachments -> /report/1/upload_attachments
2018-11-03 18:37:22 - TypeError - no implicit conversion of nil into String:
	<redacted>/Serpico/routes/report.rb:66:in `+'
	<redacted>/Serpico/routes/report.rb:66:in `block (2 levels) in <top (required)>'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/collection.rb:508:in `block in each'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `block in each'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `each'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `each'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/collection.rb:505:in `each'
	<redacted>/Serpico/routes/report.rb:63:in `block in <top (required)>'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1002:in `route!'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/show_exceptions.rb:22:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
	<redacted>/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
	<redacted>/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	<redacted>/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	<redacted>/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by arikalfus** [comment]
It looks like images can be uploaded as they appear when using the `[ ]` syntax to include in a finding. So the issue lies with trying to view the uploaded images when selecting "List Attachments."

**Comment by arikalfus** [comment]
I cleared my attachments folder and re-uploaded my pictures. They now display without a problem. Looks like the issue was with a badly named image, although I cannot tell which one it was.
